### ISSUE TITLE
Database is DOWN

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#570]
Tried going through steps from issue #565 , this is not the same problem

created Urgent case ( Case ID: 1696116871 ) via AWS Management Console, Support Center ( 1-hour turnaround )
See snapshots in issue #562 

![screen shot 2016-03-25 at 3 31 26 am](https://cloud.githubusercontent.com/assets/2165796/14042749/1de8c71e-f23a-11e5-95a3-20731aba56c3.png)

**Comment by buck0land** [comment]
Leo.   I got us back up.   re need to go over the restart order of the EC2

**Comment by NYU-AMS** [comment]
Call me when you can and I'll  give you the details

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On Mar 25, 2016, at 9:42 AM, buck0land <notifications@github.com> wrote:

Leo. I got us back up. re need to go over the restart order of the EC2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/570#issuecomment-201284206>

**Comment by leobardoramon** [comment]
Okay, so this IS the same as the Issue #565 

There were some steps that Andrew did before I jumped into the conversation

 - volumes needed to be remounted to PRODFILES

To be added to Issue #567 

Snapshot directions

Startup directions

Reboot directions

Closing this issue now
