### ISSUE TITLE
CPU Utilization Spikes

### ISSUE THREAD

**Issue by leobardoramon** [gosha1128/NYUAMS#574]
Spikes have been a daily occurrences, they are believed to have originated from the creation of a New Order on Thursday 5/19/2016:
>Leo,
>
>I'm tracking a patten of CPU alarms on AWS.
>
>It maybe related to a crash Last week. Thursday >we tried to upload 6 files that were ~1.5GB each >and it knocked prodfiles off line.  I got that up and >running but I think we have some data hanging in >the system from that crash.  Let talk about this >some time this week.  I sent you all the alarms 
>
>Andrew Buckland
>Technical lead, LaGuardia Studio (LGS) 
>Senior Advanced Media Specialist
>Academic Technology Services, IT 
>
>New York University
>545 Laguardia Place
>New York, New York 10012
>
>Phone:(212)998-3610
>email: andrew.buckland@nyu.edu

See the spike log I've created here:
https://docs.google.com/a/codetodesign.com/spreadsheets/d/1pwBa0F5SbJk_kQPiVhc9d6EGPiRTZtPfAs9wYknQ9pA/edit?usp=docslist_api

Does anyone notice any patterns or other connections?

**Comment by gosha1128** [comment]
Great.

Try to confirm you see / don't see the spike on the DEV system.

Thanks !

-g

**Comment by gosha1128** [comment]
...actually, not is now necessary...can you see if you are seeing similar
spikes on DEV for this activity...

-g

**Comment by leobardoramon** [comment]
The spikes are not happening now.

I will reproduce identical order parameters and see if any recurring
behaviors occur
...actually, not is now necessary...can you see if you are seeing similar
spikes on DEV for this activity...

-g

On Tue, May 24, 2016 at 4:15 PM, George Williams <george.williams@gmail.com>
wrote:

> Great.
>
> Try to confirm you see / don't see the spike on the DEV system.
>
> Thanks !
>
> -g
>
> On Tue, May 24, 2016 at 3:46 PM, leobardoramon <notifications@github.com>
> wrote:
>
>> Spikes have been a daily occurrences, they are believed to have
>> originated from the creation of a New Order on Thursday 5/19/2016:
>>
>> Leo,
>>
>> I'm tracking a patten of CPU alarms on AWS.
>>
>> It maybe related to a crash Last week. Thursday >we tried to upload 6
>> files that were ~1.5GB each >and it knocked prodfiles off line. I got
that
>> up and >running but I think we have some data hanging in >the system from
>> that crash. Let talk about this >some time this week. I sent you all the
>> alarms
>>
>> Andrew Buckland
>> Technical lead, LaGuardia Studio (LGS)
>> Senior Advanced Media Specialist
>> Academic Technology Services, IT
>>
>> New York University
>> 545 Laguardia Place
>> New York, New York 10012
>>
>> Phone:(212)998-3610
>> email: andrew.buckland@nyu.edu
>>
>> See the spike log I've created here:
>>
>>
https://docs.google.com/a/codetodesign.com/spreadsheets/d/1pwBa0F5SbJk_kQPiVhc9d6EGPiRTZtPfAs9wYknQ9pA/edit?usp=docslist_api
>>
>> Does anyone notice any patterns or other connections?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gosha1128/NYUAMS/issues/574>
>>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221469822>

**Comment by buck0land** [comment]
Just to add a little info to this the cup spicks are only happening on prod
3.

I think when the crash happen prod3 was in uses talking to prodfiles.  It
looked like prodfiles dumped prob3 when we were uploading the files.

Leo I will get you the files that had the we had the problem with.

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On May 25, 2016, at 3:06 AM, leobardoramon <notifications@github.com> wrote:

The spikes are not happening now.

I will reproduce identical order parameters and see if any recurring
behaviors occur
...actually, not is now necessary...can you see if you are seeing similar
spikes on DEV for this activity...

-g

On Tue, May 24, 2016 at 4:15 PM, George Williams <george.williams@gmail.com>
wrote:

> Great.
>
> Try to confirm you see / don't see the spike on the DEV system.
>
> Thanks !
>
> -g
>
> On Tue, May 24, 2016 at 3:46 PM, leobardoramon <notifications@github.com>
> wrote:
>
>> Spikes have been a daily occurrences, they are believed to have
>> originated from the creation of a New Order on Thursday 5/19/2016:
>>
>> Leo,
>>
>> I'm tracking a patten of CPU alarms on AWS.
>>
>> It maybe related to a crash Last week. Thursday >we tried to upload 6
>> files that were ~1.5GB each >and it knocked prodfiles off line. I got
that
>> up and >running but I think we have some data hanging in >the system from
>> that crash. Let talk about this >some time this week. I sent you all the
>> alarms
>>
>> Andrew Buckland
>> Technical lead, LaGuardia Studio (LGS)
>> Senior Advanced Media Specialist
>> Academic Technology Services, IT
>>
>> New York University
>> 545 Laguardia Place
>> New York, New York 10012
>>
>> Phone:(212)998-3610
>> email: andrew.buckland@nyu.edu
>>
>> See the spike log I've created here:
>>
>>
https://docs.google.com/a/codetodesign.com/spreadsheets/d/1pwBa0F5SbJk_kQPiVhc9d6EGPiRTZtPfAs9wYknQ9pA/edit?usp=docslist_api
>>
>> Does anyone notice any patterns or other connections?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gosha1128/NYUAMS/issues/574>
>>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221469822>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221490731>

**Comment by NYU-AMS** [comment]
I would like to take prod3 off line it's running at 50% load at all time
let me know if I can do this. Leo we should rebuild it.

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On May 25, 2016, at 7:16 AM, buck0land <notifications@github.com> wrote:

Just to add a little info to this the cup spicks are only happening on prod
3.

I think when the crash happen prod3 was in uses talking to prodfiles. It
looked like prodfiles dumped prob3 when we were uploading the files.

Leo I will get you the files that had the we had the problem with.

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On May 25, 2016, at 3:06 AM, leobardoramon <notifications@github.com> wrote:

The spikes are not happening now.

I will reproduce identical order parameters and see if any recurring
behaviors occur
...actually, not is now necessary...can you see if you are seeing similar
spikes on DEV for this activity...

-g

On Tue, May 24, 2016 at 4:15 PM, George Williams <george.williams@gmail.com>
wrote:

> Great.
>
> Try to confirm you see / don't see the spike on the DEV system.
>
> Thanks !
>
> -g
>
> On Tue, May 24, 2016 at 3:46 PM, leobardoramon <notifications@github.com>
> wrote:
>
>> Spikes have been a daily occurrences, they are believed to have
>> originated from the creation of a New Order on Thursday 5/19/2016:
>>
>> Leo,
>>
>> I'm tracking a patten of CPU alarms on AWS.
>>
>> It maybe related to a crash Last week. Thursday >we tried to upload 6
>> files that were ~1.5GB each >and it knocked prodfiles off line. I got
that
>> up and >running but I think we have some data hanging in >the system from
>> that crash. Let talk about this >some time this week. I sent you all the
>> alarms
>>
>> Andrew Buckland
>> Technical lead, LaGuardia Studio (LGS)
>> Senior Advanced Media Specialist
>> Academic Technology Services, IT
>>
>> New York University
>> 545 Laguardia Place
>> New York, New York 10012
>>
>> Phone:(212)998-3610
>> email: andrew.buckland@nyu.edu
>>
>> See the spike log I've created here:
>>
>>
https://docs.google.com/a/codetodesign.com/spreadsheets/d/1pwBa0F5SbJk_kQPiVhc9d6EGPiRTZtPfAs9wYknQ9pA/edit?usp=docslist_api
>>
>> Does anyone notice any patterns or other connections?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gosha1128/NYUAMS/issues/574>
>>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221469822>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221490731>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/gosha1128/NYUAMS/issues/574#issuecomment-221543491>

**Comment by leobardoramon** [comment]
PROD3 is offline.  Closing for now.
